# Generated by Django 5.1.6 on 2025-03-11 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_dentista'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Per_crear_cita', models.BooleanField(default=False)),
                ('Per_eliminar_cita', models.BooleanField(default=False)),
                ('Per_ver_cita', models.BooleanField(default=False)),
                ('Per_act_pac', models.BooleanField(default=False)),
                ('secretaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
